version: "3.9"

services:
  telegram-bot:
    container_name: telegram-bot
    working_dir: /telegram_bot
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python bot_aiogram.py"